name: speedometer
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  location: ^6.0.2
  hive_flutter: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
